### ISSUE TITLE
Adding Some Features

### ISSUE THREAD

**Issue by JeffHoogland** [corecomic/pyrrha#5]
Hey There - not an actual issue but wanted to ask about a few things before I forked and take a crack at them. I want to try and add the following to Pyrrha:

* Lock screen controls for play/pause and skip song
* Multi-Media controls for skip song and play / pause from a device such as a bluetooth headset
* Output of the current song name / artist / album to devices like in car audio

Just wanted to ask if you'd taken a crack at any of these before I dig into trying to add them myself.

Cheers for a great application as well.

**Comment by corecomic** [comment]
Hi Jeff, thanks for asking!

These things are actually implemented (using MPRIS) in the master branch and published on OpenRepos, unfortunately not allowed in the Jolla store, therefore missing there.

Lock screen controls and controls from a headset I've tested. Not sure what information is passed on to devices, probably possible to add more stuff there.

I'd gladly integrate changes to improve it.

**Comment by JeffHoogland** [comment]
Awesome! Grabbed the version from open resources and the lock screen controls are great. Will try the bluetooth controls next time I'm in my car. Glad I asked before poking at this too much myself.

I'll google around to see if there is a python library for sending song information to bluetooth devices and make a pull request when I get the details sorted.
